export const CHANGE_SMASH_TITLE = "CHANGE_SMASH_TITLE";
export const SET_BRACKET_ROUND = "SET_BRACKET_ROUND";
export const SET_VOD_LINK = "SET_VOD_LINK";
export const SET_BRACKET_LINK = "SET_BRACKET_LINK";
